[package]
name = "redis-clone-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
# Standard error handling libraries
thiserror = "2.0.17"   # For defining error types
anyhow = "1.0.100"    # For error context and propagation

tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"